apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: skaffold-demo/spring
      context: api/spring
      jib:
        project: api:spring
    - image: skaffold-demo/micronaut
      context: api/micronaut
      jib:
        project: api:micronaut
    - image: skaffold-demo/angular
      context: web/angular
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
        - 'src/**'
    - image: skaffold-demo/react
      context: web/react
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
        - 'src/**'

deploy:
  statusCheckDeadlineSeconds: 240
  kubectl:
    manifests:
      - k8s-mysql.yaml
      - k8s-shared-environment.yaml
      - api/spring/k8s.yaml
      - api/micronaut/k8s.yaml
      - web/angular/k8s.yaml
      - web/react/k8s.yaml