---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
data:
  SPRING_PROFILES_ACTIVE: skaffold
  SPRING_DATASOURCE_USERNAME: skaffold
  SPRING_DATASOURCE_PASSWORD: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'skaffold'@'%' IDENTIFIED BY 'password';
    CREATE DATABASE IF NOT EXISTS quotes;
    GRANT ALL ON *.* TO 'skaffold'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: bitnami/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
