---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mysql
          command: ['sh', '-c', 'until mysql -h mysql -u skaffold -ppassword -e "use quotes"; do sleep 5; done']
      containers:
        - name: spring-demo
          image: skaffold-demo/spring
          envFrom:
          - configMapRef:
              name: shared-environment
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo
  labels:
    name: spring-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
  - http:
      paths:
      - path: /api/spring/(.*)
        backend:
          serviceName: spring-demo
          servicePort: 80