---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micronaut-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micronaut-demo
  template:
    metadata:
      labels:
        app: micronaut-demo
    spec:
      containers:
        - name: micronaut-demo
          image: skaffold-demo/micronaut
          envFrom:
          - configMapRef:
              name: shared-environment
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: micronaut-demo
  labels:
    name: micronaut-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: micronaut-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micronaut-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
  - http:
      paths:
      - path: /api/micronaut/(.*)
        backend:
          serviceName: micronaut-demo
          servicePort: 80