---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
        - name: node-demo
          image: skaffold-demo/node
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-demo
  labels:
    name: node-demo
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
  - http:
      paths:
      - path: /api/node/(.*)
        backend:
          serviceName: node-demo
          servicePort: 80