---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-demo
spec:
  selector:
    matchLabels:
      app: angular-demo
  template:
    metadata:
      labels:
        app: angular-demo
    spec:
      containers:
      - name: angular-demo
        image: skaffold-demo/angular
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: angular-demo
spec:
  selector:
    app: angular-demo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: angular-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /angular/(.*)
        backend:
          serviceName: angular-demo
          servicePort: 80